### ISSUE TITLE
Feature request: support for jar files

### ISSUE THREAD

**Issue by lucasgonze** [pillsilly/recursive-unzipper#6]
A complex bundle of compressed files will often have jar files in it. If recursive-unzipper knew how to unzip them, it would be helpful.

**Comment by pillsilly** [comment]
A jar is basically different from zip at their file name extension which is in fact, not mattered to how the file could be extracted,
so I guess it's doable:
by just letting user pass some format option to indicate which file format to be treated as which extraction method.

**Comment by lucasgonze** [comment]
> so I guess it's doable:

I appreciate you putting up with this slightly flaky idea. 

The role of recursive-unzipper in my workflow is to make something rational happen given an input file that is a mess.  The top-level file might contain all kinds of madness, including .rar, .jar, .gz, .bz, .zip, .tar, or even files that are simply corrupt.

**Comment by pillsilly** [comment]
#7 is merged

latest version should work regarding to this topic @lucasgonze

**Comment by lucasgonze** [comment]
Great! Thank you so much!
