### ISSUE TITLE
feat: make -f optional

### ISSUE THREAD

**Issue by lucasgonze** [pillsilly/recursive-unzipper#8]
The program has one required argument, a file to unzip. `recursive-unzipper myfile.tgz` should do something useful. 

But the program requires -f before the filename. This adds verbosity with little benefit.

Feature request: if -f is omitted, assume the remaining parameter is a file.

**Comment by lucasgonze** [comment]
I am poking around in the Commander API. I haven't yet found a clean way to do it.

**Comment by lucasgonze** [comment]
I have some understanding of what to do with Commander. Can you document the assumptions to run in a dev environment? There is no "run" script.

**Comment by pillsilly** [comment]
> I have some understanding of what to do with Commander. Can you document the assumptions to run in a dev environment? There is no "run" script.

I studied it a little bit as well and it seems "Arguments" are what we're looking for.

Implementation would be like:

https://github.com/pillsilly/recursive-unzipper/pull/10/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

Also you reminded  me to add a **Development** section to ease the others to try the code.
At the moment you can simply use 
`npm run test`
to run near-e2e tests
 

or
`/recursive-unzipper$ npx ts-node ./src/bin.ts -f abc.zip ....`
to execute the code directly.
